name: Publish

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  BUILD_CONFIGURATION: 'Release'
  DOTNET_VERSION: '7.0.x'
  PACKAGE_ID: Onest.HeroIcons
  PACKAGE_DIRECTORY: ${{ github.workspace }}/package
  GITHUB_PACKAGE_REGISTRY_URL: https://nuget.pkg.github.com/enejsimrajh/index.json

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          source-url: ${{ env.GITHUB_PACKAGE_REGISTRY_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version from tag
        run: echo "PACKAGE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Build and create a package
        run: |
          dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} /p:Version=$PACKAGE_VERSION
          dotnet pack --configuration ${{ env.BUILD_CONFIGURATION }} /p:Version=$PACKAGE_VERSION --output ${{ env.PACKAGE_DIRECTORY }} --no-build
        working-directory: src
      - name: Upload a build artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ env.PACKAGE_ID }}-${{ env.PACKAGE_VERSION }}
          path: ${{ env.PACKAGE_DIRECTORY }}/*.nupkg
          if-no-files-found: error
          retention-days: 7
      - name: Publish the package to GPR
        run: dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/*.nupkg
