name: Publish NuGet package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          source-url: https://nuget.pkg.github.com/enejsimrajh/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get version from tag
        run: echo "PACKAGE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release /p:Version=$PACKAGE_VERSION
        working-directory: src
      - name: Create the package
        run: dotnet pack --configuration Release --no-build /p:Version=$PACKAGE_VERSION
        working-directory: src
      - name: Publish the package to GPR
        run: dotnet nuget push src/Onest.HeroIcons/bin/Release/*.nupkg
